---
- ansible.builtin.import_tasks: ../../common-tasks/vault_login/vault_login.yaml

- name: Aquire consul token from vault
  run_once: true
  delegate_to: localhost
  become: false
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ vault_token }}"
  ansible.builtin.command: |
    vault read -field=token \
      consul/creds/global_management_role
  register: consul_token_out

- ansible.builtin.set_fact:
    consul_token: "{{ consul_token_out.stdout }}"
