---
- ansible.builtin.import_tasks: ../../common-tasks/hashicorp_repository/hashicorp_repository.yaml

- name: Install envconsul
  ansible.builtin.apt:
    name: envconsul
    state: latest
    update_cache: true

- name: Ensure envconsul directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "770"
  with_items:
    - "{{ envconsul.data_dir }}"
    - "{{ envconsul.config_dir }}"

- name: Copy envconsul service
  ansible.builtin.template:
    src: "envconsul@.service.j2"
    dest: "{{ systemd_dir }}/envconsul@.service"
