---
# @meta description: >
# Install Vault
# @end

- ansible.builtin.import_tasks: ../../common-tasks/hashicorp_repository/hashicorp_repository.yaml

- name: Install vault package
  ansible.builtin.apt:
    name: vault
    state: latest
    update_cache: true

- name: Ensure vault service is enabled
  ansible.builtin.service:
    name: vault
    state: started
    enabled: true
