---
# @meta description: >
# Install Consul
# @end

- ansible.builtin.import_tasks: ../../common-tasks/hashicorp_repository/hashicorp_repository.yaml

- name: Install Consul package
  ansible.builtin.apt:
    name: consul
    state: latest

- name: Ensure consul service is enabled
  ansible.builtin.service:
    name: consul
    enabled: true
