---
- name: Copy policy to working directory
  ansible.builtin.copy:
    src: "acl_{{ item }}_policy.hcl"
    dest: /tmp/consul/acl/

- name: Create {{ item }} policy
  ansible.builtin.command: |
    consul acl policy create \
      -token {{ management_token }} \
      -name {{ item }}_policy \
      -rules @/tmp/consul/acl/acl_{{ item }}_policy.hcl
  register: create_policy_out
  failed_when: create_policy_out.rc != 0 and 'already exists' not in create_policy_out.stderr

- name: Update {{ item }} policy if exists
  ansible.builtin.command: |
    consul acl policy update \
      -token {{ management_token }} \
      -name {{ item }}_policy \
      -rules @/tmp/consul/acl/acl_{{ item }}_policy.hcl
  when: create_policy_out.rc != 0 and 'already exists' in create_policy_out.stderr

- name: Create vault role for {{ item }} policy
  ansible.builtin.command: |
    vault write consul/roles/{{ item }}_role \
      policies={{ item }}_policy

- name: Get {{ item }} token
  ansible.builtin.command: |
    vault read -field=token consul/creds/{{ item }}_role
  register: token_out

- ansible.builtin.set_fact: { "{{ item }}_token": "{{ token_out.stdout }}" }
