---
- ansible.builtin.import_tasks: ../../common-tasks/vault_login/vault_login.yaml

- name: Aquire nomad token from vault
  run_once: true
  delegate_to: localhost
  become: false
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ vault_token }}"
  ansible.builtin.command: |
    vault read -field=secret_id \
      nomad/creds/global_management_role
  register: nomad_token_out

- ansible.builtin.set_fact:
    nomad_token: "{{ nomad_token_out.stdout }}"
