---
- import_playbook: prepare.yaml
  tags:
    - prepare

- import_playbook: install.yaml
  tags:
    - install

- import_playbook: configure.yaml
  tags:
    - configure

- import_playbook: configure_admin.yaml
  tags:
    - configure_admin
