---
- ansible.builtin.import_tasks: ../../common-tasks/nomad_login/nomad_login.yaml

- name: Ensure working directory
  ansible.builtin.file:
    path: /tmp/vector/install
    state: directory

- name: Get log_shipper_api_key from HCPVS # HCP Vault Secrets
  ansible.builtin.command: |
    vlt secrets get \
      -p {{ hcpvs.project_id }} \
      -a Grafana \
      -plaintext log_shipper_api_key
  register: log_shipper_api_key_out

- ansible.builtin.set_fact:
    log_shipper_api_key: "{{ log_shipper_api_key_out.stdout }}"

- name: Prepare vector job file
  ansible.builtin.template:
    src: vector.nomad.j2
    dest: /tmp/vector/install/vector.nomad

- name: Deploy Vector nomad job
  ansible.builtin.command: |
    nomad job run \
      -address={{ nomad.url }} \
      -token={{ nomad_token }} \
      /tmp/vector/install/vector.nomad
