name: Ensure as less missconfigurations as possible

on:
  push:

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      #- name: Run ansible-lint
      #  uses: ansible/ansible-lint-action@main
    - name: Run ansible-lint
      # replace `main` with any valid ref, or tags like `v6`
      uses: ansible-community/ansible-lint-action@v6.0.2
      with:
        args: "ansible" # my ansible files in a folder
  Security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run kics scan
      uses: checkmarx/kics-github-action@v1.7.0
      with:
        path: ./
        output_path: kics-results/
        fail_on: high,medium
        type: Ansible
