name: Ensure as less missconfigurations as possible

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run scan
      uses: checkmarx/kics-github-action@v1.7.0
      with:
        path: ./
        output_path: kics-results/
        fail_on: high,medium
        type: Ansible
    - name: Display results
      run: cat kicsk-results/results.json
